BoxLayout:
    orientation: "vertical"
    BoxLayout:
        orientation: 'horizontal'
        TextInput:
            id: input_number
            text: ''
            font_size: 48
            multiline: False
        BoxLayout:
            orientation: "vertical"
            Button:
                text: 'Up'
                on_press: handle_increment(1)
            Button:
                text: 'Down'
                on_press: handle_increment(-1)